name: Unit tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  checks:
    name: Run clippy and unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run cargo fmt
        shell: bash
        run: |
          cargo fmt --all -- --check

      - name: Run clippy
        shell: bash
        run: |
          cargo clippy --all-targets -- --no-deps -D warnings

      - name: Run unit tests
        run: make test

  build:
    name: Build the contract
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build contract
        run: make build
